package main

import (
	"TTU_CORE_ERP_API/configs"
	"TTU_CORE_ERP_API/repositories"
	"TTU_CORE_ERP_API/routes"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	fiberSwagger "github.com/swaggo/fiber-swagger"
	_ "github.com/swaggo/fiber-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title TTU Integration API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	app := fiber.New()
	db := database.Init()
	/*err := database.Migrate()
	if err != nil {
		return
	}*/
	app.Get("/", fiberSwagger.WrapHandler)
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	repositories.DB = db
	app.Use(cors.New(cors.Config{
		AllowCredentials: true,
		AllowOrigins:     "*",
	}))

	// Use logger
	app.Use(logger.New())

	routes.Setup(app)

	app.Listen(":5000")

}
